  name: Development

  on:
    push:
      branches:
        - UipathCICD

  # Here the environment variable is declared in workflow level
  env:
    # Replace with your Orchestrator Values
    PROJECT_NAME: uipath.github.action
    PROJECT_FOLDER: ${{ github.action_path }}
    ORCH_URL: https://cloud.uipath.com/rxomafmgxr/NonProd
    ORCH_TENANT: ${{ secrets.ORCHESTRATOR_TENANT }}
    ORCH_CLIENT_ID: ${{ secrets.ORCH_CLIENTID }}
    ORCH_USER_KEY: ${{ secrets.USERKEY }}
    ORCH_ACC_NAME: ${{ secrets.ACCOUNT_NAME }}

  jobs:
    print-details:
      runs-on: ubuntu-latest
      steps:
        - name: echo-default-env-variables
          run: |
            echo "Home: ${HOME}"
            echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
            echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
            echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
            echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
            echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
            echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
            echo "GITHUB_SHA: ${GITHUB_SHA}"
            echo "GITHUB_REF: ${GITHUB_REF}"
    cleaner:
      runs-on: ubuntu-latest
      steps:
        - name: Runner workspace path
          run: |
            echo "Cleaning up previous run"
            rm -rf "${{ github.workspace }}"

    build-uipath-nuget-package:
      # You should be able to run on windows 2019 or windows latest
      needs: cleaner
      runs-on: windows-latest
      steps:
        - name: Check out repository code
          # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
          uses: actions/checkout@v2
        - name: Build Nuget Package
          shell: pwsh
          run: ${{ github.workspace }}\scripts\UiPathPack.ps1 ${{ github.workspace }}\project.json -destination_folder ${{ github.workspace }}\package
        - name: Upload UiPath Artifacts
          uses: actions/upload-artifact@v2
          with:
            name: Artifacts
            path: |
            package: /*.nupkg
            scripts: /*.ps1
    publish-uipath-nuget-package:
      needs: build-uipath-nuget-package
      runs-on: windows-latest
      steps:
        - name: Download UiPath Artifacts
          uses: actions/download-artifact@v2
          with:
            name: Artifacts
        - name: Publish Nuget Package to DEV
          shell: pwsh
          run: ${{ github.workspace }}\scripts\UiPathDeploy.ps1 ${{ github.workspace }}\package ${{env.ORCH_URL}} ${{env.ORCH_TENANT}} -UserKey ${{env.ORCH_USER_KEY}} -account_name ${{env.ORCH_ACC_NAME}}

